title = "Throttler server configuration"

[groups]

[groups.default]
# mandatory group that's used when no other group is found.
max_parallel = 12 # total global limit of parallel processes
priority = 100    # higher priority comes first

[groups.compile]
max_parallel = 12
priority =     50 # higher priority is always scheduled before lower priority

[groups.link]
max_parallel = 4  # no more than 4 concurrent linking processes
priority = 200    # have a higher priority than compile
