
num_threads = 12
default_priority = 100

[group.compile]
max_parallel = 12
priority =     50 # higher priority is always scheduled before lower priority

[group.link]
max_parallel = 2  # no more than 4 concurrent linking processes
priority = 200    # have a higher priority than compile
